### ISSUE TITLE
building libjit.dll

### ISSUE THREAD

**Issue by raizam** [ademakov/libjit#10]
hi, I was looking for an easy jit library, with a C interface, and libjit seems all I could hope for.
But I have no knowledge of the linux dev at all.

I've cloned the sources, installed MinGw, and selected a lot of MSys packages, googled a lot, and I'm stuck.

I first had to downgrade configure.ac from 2.69 to 2.68 (hoping I'm not breaking anything)
from MinGW bash: 
```
$ autoconf-2.68
configure.ac:14: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:108: error: possibly undefined macro: AM_PROG_AR
configure.ac:113: error: possibly undefined macro: AM_PROG_LEX
```
it shows error but still generated the configure file, then it tried to run
```
$ configure
configure: error: cannot find install-sh, install.sh, or shtool in build-aux "."
/build-aux
```

So now I'm here, and I don't know what to do. libjit looks very nice, but feels unfriendly to windows users, and doesn't support win64 :/

**Comment by ademakov** [comment]
Do you have automake installed?

**Comment by raizam** [comment]
Yes, msys-automake version `1.11.1-1-msys-1.0.13`
This issue isn't important to me anymore, I'm now using LLVM.
