### ISSUE TITLE
Some documented functions are not declared

### ISSUE THREAD

**Issue by tromey** [ademakov/libjit#20]
I noticed that `jit_compile`, `jit_optimize`, and `jit_compile_entry` are documented but not declared in any header.  Should they be un-documented (and perhaps renamed), or declared?

**Comment by M4GNV5** [comment]
:+1: it is interesting to see the output of `jit_dump_function` before and after `jit_optimize`

**Comment by tromey** [comment]
I wrote a script to check for this kind of mistake and it found a few more.  I'll submit shortly.
