### ISSUE TITLE
Throwing exceptions from a libjit function

### ISSUE THREAD

**Issue by yuvalpick** [ademakov/libjit#24]
Hi,
I’m using libjit to generate code thats calls a c++ function using the jit function jit_insn_call_native.
This c++ function may throw exceptions (e.g. out_of_range exception), I would like to catch this exception in the libjit function we created and return an error code (instead of throwing an exception).

Is this something we can do?

**Comment by M4GNV5** [comment]
Hey,
I assume the most portable way is to write an `extern C` function that wraps a call to `jit_apply` in a try/catch.

Something like this:
```C++
extern "C" {

int cpp_caller(jit_type_t signature, void *func, void **args, unsigned num_args, void *return_val) {
   try {
       jit_apply(signature, func, args, num_args, return_val);
       return 0;
   } catch (const std::exception& ex) {
       return 1;
   }
}

}
```

You would then call `cpp_caller` from your JIT code using `jit_insn_call_native` and pass the function you actually want to call as well as the arguments to it as defined [in the libjit docs of jit_apply](https://www.gnu.org/software/libjit/doc/libjit_15.html#Function-application-and-closures)

The alternative faster but way less portable way is to check how your environment implements exceptions (is it a special return, or a setjmp/longjmp, etc.) and then mimic this behaviour in libjit, but the above approach is probably a better idea unless you specificly only want to target a single plattform+architecture+ABI.

Also feel free to ask these kind of questions on the mailing list.

**Comment by yuvalpick** [comment]
Oh great!
This seems exactly what I was looking for.

Thanks!
