### ISSUE TITLE
Question: libjit status

### ISSUE THREAD

**Issue by dibyendumajumdar** [ademakov/libjit#3]
Hi,

I am interested in using libjit as the backend in my C JIT compiler project (https://github.com/dibyendumajumdar/dmr_c). I was wondering how stable and well tested libjit is - I noticed that there aren't many tests in the project. 

Thanks and Regards
Dibyendu

**Comment by ademakov** [comment]
It was used as a backend for Portable.NET and was tested well enough then. Other users sometimes find bugs but it happens not very often. Partially this is because there are not that many users, but libjit own quality also plays a role.

**Comment by dibyendumajumdar** [comment]
Okay thank you. Couple of more questions:

1) Is it possible to build libjit on Windows using MSVC?
2) If bugs are discovered then are you actively fixing them?

**Comment by dibyendumajumdar** [comment]
Hi,
I also understand that libjit has a register allocator, and also does liveness analysis?

**Comment by ademakov** [comment]
1. It should be possible to build it with mingw32. Win64 will not work.
2. If time permits. Feel free to submit patches though.

**Comment by dibyendumajumdar** [comment]
Okay thank you for the information. I will hopefully be able to try out libjit later in the year.
