### ISSUE TITLE
Is it possible to change the license of libjit?

### ISSUE THREAD

**Issue by dibyendumajumdar** [ademakov/libjit#4]
Hi,

I was wondering if it is possible to change the license of libjit? It seems that libjit copyright has not been assigned to FSF - is my understanding correct? If so, then are there reasons why the license could not be changed to MIT ?

I think it will make libjit a viable alternative to some other tools.

Regards
Dibyendu

**Comment by ademakov** [comment]
It would require to collect approval from all the contributors. And I think LGPL is already good enough. It used to be GPL. Also libjit is an official GNU package.

https://www.gnu.org/software/libjit/

I believe it is better to stay with GNU.
